[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.22"
authors = ["Trim21 <trim21.me@gmail.com>"]
edition = "2024"
homepage = "https://github.com/trim21/beancount-format"
license = "MIT"
repository = "https://github.com/trim21/beancount-format"
description = "Beancount formatter library and tooling."

[workspace.dependencies]
anyhow = "1.0.100"
beancount-formatter = { path = "./crates/beancount-formatter/" }
beancount-parser = { git = "https://github.com/trim21/beancount.git", rev = "04fa3cef8024afe7f4b4f03bcecfb0a86e914172" }
serde = { version = "1.0.228", features = ["derive"] }

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
