[workspace]
members = [
  "crates/beancount-formatter",
  "crates/beancount-formatter-cli",
  "crates/dprint-plugin-beancount",
  "crates/beancount-formatter-py",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["David Sherret <dsherret@gmail.com>"]
homepage = "https://github.com/dprint/dprint-plugin-beancount"
license = "MIT"
repository = "https://github.com/dprint/dprint-plugin-beancount"
description = "Beancount formatter for dprint."

[workspace.dependencies]
anyhow = "1.0.64"
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.144", features = ["derive"] }
dprint-core = { version = "0.67.4", features = ["formatting"] }

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
