[package]
name = "beancount-formatter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Core beancount formatter logic."

[dependencies]
tree-sitter-beancount = { git = "https://github.com/trim21/tree-sitter-beancount", rev = "041991d9509050cb5b5d88194f378cecb1452c26" }
tree-sitter = { version = "0.26.3" }
anyhow.workspace = true
serde.workspace = true
ropey = '*'
