[package]
name = "beancount-formatter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Core beancount formatter logic."

[features]
default = ["std"]
std = ["tree-sitter-beancount/std"]
wasm = ["tree-sitter-beancount/wasm"]

[dependencies]
tree-sitter-beancount = { git = "https://github.com/trim21/tree-sitter-beancount", branch = "wasm", default-features = false }
# tree-sitter-beancount = { path = "C:/Users/trim21/projects/tree-sitter-beancount/", default-features = false }
tree-sitter = { version = "0.26.3" }
anyhow.workspace = true
serde.workspace = true
ropey = '1.6.1'

[dev-dependencies]
serde_json = "1"
similar = { version = "2.7.0", features = ["unicode"] }
