[package]
name = "beancount-formatter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Core beancount formatter logic."

[dependencies]
tree-sitter-beancount = "2.4.2"
tree-sitter = "*"
anyhow.workspace = true
serde.workspace = true
ropey = '*'
