[package]
name = "beancount-formatter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Core beancount formatter logic."

[features]
default = ["std"]
std = ["tree-sitter-beancount/std"]
wasm = ["tree-sitter-beancount/wasm", "tree-sitter-language"]

[dependencies]
tree-sitter-beancount = { git = "https://github.com/trim21/tree-sitter-beancount", rev = "906f746dc43d977ca379373c380eea992de81120", default-features = false }
tree-sitter = { version = "0.26.3" }
tree-sitter-language = { optional = true, version = "^0.1.6"}
# tree-sitter-language = { optional = true, git = "https://github.com/trim21/tree-sitter.git" }
anyhow.workspace = true
serde.workspace = true
ropey = '*'
