[package]
name = "beancount-formatter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Core beancount formatter logic."

[dependencies]
beancount-parser = { git = "https://github.com/trim21/beancount.git", rev = "44c4df3c" }
# beancount-parser = { path = "../../../beancount/beancount/" }
# beancount-parser = { path = "../../../beancount/beancount/crates/beancount-parser/" }
tree-sitter = { version = "0.26.3" }
anyhow.workspace = true
serde.workspace = true
ropey = '1.6.1'

[dev-dependencies]
serde_json = "1.0.149"
similar = { version = "2.7.0", features = ["unicode"] }
