[package]
name = "beancount-formatter"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
description = "Core beancount formatter logic."

[dependencies]
anyhow.workspace = true
beancount-parser = { git = "https://github.com/trim21/beancount.git", rev = "448580ff00595f9d9b8b4d81b385df4b069a1f3b" }
ropey = '1.6.1'
serde.workspace = true
# beancount-parser = { path = "../../../beancount/beancount/" }
# beancount-parser = { path = "../../../beancount/beancount/crates/beancount-parser/" }
tree-sitter = { version = "0.26.3" }

[dev-dependencies]
serde_json = "1.0.149"
similar = { version = "2.7.0", features = ["unicode"] }
