[package]
name = "beancount-formatter-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "CLI for the beancount formatter."
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
beancount-formatter = { workspace = true }

[[bin]]
name = "beancount-formatter"
path = "src/main.rs"
