[package]
name = "dprint-plugin-beancount"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Beancount formatter for dprint."

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
wasm = ["dprint-core/wasm"]

[dependencies]
anyhow.workspace = true
dprint-core = { version = "0.67.4", features = ["formatting", "wasm"] }
beancount-formatter = { path = "../beancount-formatter" }
