[package]
name = "dprint-plugin-beancount"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Beancount formatter for dprint."

[features]
default = []
wasm = ["dprint-core/wasm"]

[lib]
# for wasm
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
dprint-core = { version = "0.67.4", features = ["formatting", "wasm"] }
beancount-formatter = { path = "../beancount-formatter", default-features = false, features = [
  'wasm'
] }
serde_json = "1.0.148"
